from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime
import os


class ReportGenerator:
    def __init__(self, output_dir="reports/generated/"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_pdf(self, session_id, avg_score, summary_advice, history_data):
        """
        生成课堂表现 PDF 报告
        history_data: [(time, score), ...]
        """
        filename = f"Report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
        filepath = os.path.join(self.output_dir, filename)

        c = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4

        # 绘制标题
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width / 2.0, height - 50, "Classroom AI System v2.0 Analysis Report")

        # 绘制基础信息
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 100, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        c.drawString(50, height - 120, f"Average Concentration Score: {avg_score}%")

        # 绘制分割线
        c.setStrokeColor(colors.lightgrey)
        c.line(50, height - 140, width - 50, height - 140)

        # 写入决策建议 (此处可根据需要增加中文支持)
        c.setFont("Helvetica-Oblique", 11)
        text_obj = c.beginText(50, height - 170)
        text_obj.textLine("Overall Teaching Feedback:")
        text_obj.setFont("Helvetica", 10)
        text_obj.textLines(summary_advice)
        c.drawText(text_obj)

        # 简单的数据列表可视化
        c.drawString(50, height - 250, "Data Points (Recent 10 Samples):")
        y_pos = height - 270
        for time_str, score in history_data[-10:]:
            c.drawString(70, y_pos, f"- [{time_str}] Focus: {score}")
            y_pos -= 15

        # 页脚
        c.setFont("Helvetica", 8)
        c.drawCentredString(width / 2.0, 30,
                            "Generated by Classroom AI Decision System - 2026 Computer Design Competition")

        c.save()
        return filepath